import { StyleSheet } from 'react-native';
import { InkColors, BrandColors } from '@/lib/theme/colors';
import { Elevation, Radius } from '@/lib/theme/elevation';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: InkColors.cream },
  scroll: { padding: 20, gap: 18 },
  greet: { fontSize: 16, fontWeight: '700', color: InkColors.ink2 },
  // 섹션: [밖 라벨] + [안 카드] 묶음
  section: { gap: 8 },

  // 상단 커스텀 헤더 — 좌측 로고 / 우측 매장명·사용자명
  appHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: 6,
    paddingBottom: 10,
    backgroundColor: InkColors.cream,
  },
  appHeaderRight: { flex: 1, alignItems: 'flex-end', paddingLeft: 12 },
  appHeaderStore: { fontSize: 16, fontWeight: '900', color: InkColors.ink, textAlign: 'right' },
  appHeaderUser: { fontSize: 12, fontWeight: '600', color: InkColors.ink3, textAlign: 'right', marginTop: 2 },

  onboard: {
    backgroundColor: BrandColors.accentSoft,
    borderRadius: Radius.lg,
    borderWidth: 1,
    borderColor: '#E8C9C2',
    padding: 20,
    gap: 8,
    alignItems: 'flex-start',
  },
  onboardEmoji: { fontSize: 34 },
  onboardTitle: { fontSize: 18, fontWeight: '900', color: InkColors.ink },
  onboardBody: { fontSize: 14, color: InkColors.ink2, lineHeight: 21 },
  onboardCta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 6,
    backgroundColor: BrandColors.brand,
    paddingVertical: 12,
    paddingHorizontal: 18,
    borderRadius: Radius.pill,
  },
  onboardCtaText: { color: InkColors.bubbleText, fontSize: 14, fontWeight: '800' },
  seedLabel: { fontSize: 12, color: InkColors.ink2, fontWeight: '700', marginTop: 12 },
  seedChips: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 8 },
  seedChip: {
    backgroundColor: InkColors.bg,
    borderWidth: 1,
    borderColor: InkColors.line,
    borderRadius: Radius.pill,
    paddingVertical: 7,
    paddingHorizontal: 12,
  },
  seedChipText: { fontSize: 12.5, fontWeight: '700', color: InkColors.ink },

  // ① 받은질문 히어로 (사령탑 주인공)
  hero: { backgroundColor: InkColors.ink, borderRadius: Radius.lg, padding: 18, gap: 7, ...Elevation.e2 },
  heroHead: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  heroKicker: { fontSize: 13, fontWeight: '800', color: InkColors.bubbleText, letterSpacing: 0.3 },
  heroBadge: {
    marginLeft: 'auto',
    minWidth: 24,
    height: 24,
    paddingHorizontal: 7,
    borderRadius: Radius.pill,
    backgroundColor: BrandColors.accent,
    alignItems: 'center',
    justifyContent: 'center',
  },
  heroBadgeText: { fontSize: 13, fontWeight: '900', color: InkColors.bubbleText },
  heroLead: { fontSize: 16, fontWeight: '700', color: InkColors.bubbleText, lineHeight: 23 },
  heroSub: { fontSize: 12, color: 'rgba(255,255,255,0.6)', lineHeight: 18 },
  heroCta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    alignSelf: 'flex-start',
    marginTop: 4,
    backgroundColor: InkColors.bg,
    paddingVertical: 9,
    paddingHorizontal: 14,
    borderRadius: Radius.pill,
  },
  heroCtaText: { fontSize: 13, fontWeight: '800', color: InkColors.ink },

  // ② 오늘 업무 요약
  todayCard: {
    backgroundColor: InkColors.bg,
    borderRadius: Radius.md,
    borderWidth: 1,
    borderColor: InkColors.line,
    padding: 18,
    gap: 10,
    ...Elevation.e1,
  },
  todayPill: {
    fontSize: 12,
    fontWeight: '700',
    color: InkColors.ink2,
    backgroundColor: InkColors.bgSoft,
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: Radius.pill,
    overflow: 'hidden',
    marginLeft: 'auto',
  },
  bar: { height: 8, borderRadius: Radius.pill, backgroundColor: InkColors.bgSoft, overflow: 'hidden' },
  barFill: { height: 8, borderRadius: Radius.pill, backgroundColor: BrandColors.yellow },
  todaySub: { fontSize: 13, color: InkColors.ink3, fontWeight: '600' },

  miniRow: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', gap: 8 },
  miniLink: { fontSize: 13, color: InkColors.ink2, fontWeight: '700' },

  faqSection: { gap: 8 },
  faqList: {
    backgroundColor: InkColors.bg,
    borderRadius: Radius.md,
    borderWidth: 1,
    borderColor: InkColors.line,
    paddingHorizontal: 14,
  },
  faqRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: InkColors.line,
  },
  faqDot: { width: 8, height: 8, borderRadius: Radius.pill },
  faqQ: { fontSize: 14, fontWeight: '600', color: InkColors.ink },
  faqMetaRow: { flexDirection: 'row', alignItems: 'center', gap: 6, marginTop: 3 },
  faqMeta: { fontSize: 12, color: InkColors.ink3 },
  // 많이 물어본 신호 — 직원 홈 popularHits와 동일(노랑 소프트 틴트 + 검정).
  faqHits: {
    fontSize: 11,
    fontWeight: '800',
    color: InkColors.ink,
    backgroundColor: BrandColors.yellowSoft,
    paddingVertical: 2,
    paddingHorizontal: 7,
    borderRadius: Radius.pill,
    overflow: 'hidden',
  },
  faqAction: { fontSize: 13, fontWeight: '800', color: BrandColors.brand },

  nudges: { gap: 10 },
});
